/*
 * Copyright (c) 2019 Actions Semiconductor Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file app ui define
 */

#ifndef _APP_UI_EVENT_H_
#define _APP_UI_EVENT_H_
#include <sys_event.h>
#include <msg_manager.h>
#include <ui_manager.h>

#ifndef CONFIG_SIMULATOR
#include <board_cfg.h>
#endif

#if CONFIG_PANEL_HOR_RES >= 454
#  include "../resource/454x454/bt_watch_sty.h"
#  include "../resource/454x454/logo_sty.h"

#define DEF_UI_WIDTH	454
#define DEF_UI_HEIGHT	454
#else
#  include "../resource/360x360/bt_watch_sty.h"
#  include "../resource/360x360/logo_sty.h"

#define DEF_UI_WIDTH	360
#define DEF_UI_HEIGHT	360
#endif /* CONFIG_PANEL_HOR_RES == 454 */

/* default ui view resolution */
#define DEF_UI_VIEW_WIDTH		CONFIG_PANEL_HOR_RES
#define DEF_UI_VIEW_HEIGHT		CONFIG_PANEL_VER_RES

// default ui file
#define DEF_UI_DISK				CONFIG_APP_UI_DISK
#define DEF_FONT_DISK			CONFIG_APP_FONT_DISK
#define DEF_STY_FILE			DEF_UI_DISK"/bt_watch.sty"
#define DEF_RES_FILE			DEF_UI_DISK"/bt_watch.res"
#define DEF_STR_FILE			DEF_UI_DISK"/bt_watch.zhC"
#define DEF_FONT22_FILE			DEF_FONT_DISK"/sans22.font"
#define DEF_FONT24_FILE			DEF_FONT_DISK"/sans24.font"
#define DEF_FONT28_FILE			DEF_FONT_DISK"/sans28.font"
#define DEF_FONT32_FILE			DEF_FONT_DISK"/sans32.font"
#define DEF_FONT28_EMOJI		DEF_FONT_DISK"/emoji28.font"

#define WELCOME_UI_DISK			CONFIG_WELCOME_UI_DISK
#define WELCOME_STY_FILE		WELCOME_UI_DISK"/logo.sty"
#define WELCOME_RES_FILE		WELCOME_UI_DISK"/logo.res"

/* configuration name definition */
#define CFG_AOD_MODE			"AOD_MODE"
#define CFG_CLOCK_ID			"CLOCK_ID"

enum {
	NEED_INIT_BT,
	NO_NEED_INIT_BT,
};

enum {
	// bt common key message
	MSG_BT_PLAY_TWS_PAIR = MSG_APP_MESSAGE_START, /* 200 */
	MSG_BT_PLAY_DISCONNECT_TWS_PAIR,
	MSG_BT_PLAY_CLEAR_LIST,
	MSG_BT_SIRI_START,
	MSG_BT_SIRI_STOP, /* 204 */
	MSG_BT_CALL_LAST_NO,
	MSG_BT_HID_START,
	MSG_KEY_POWER_OFF,
	MSG_BT_APP_MESSAGE_START, /* 208 */
	MSG_BT_TWS_SWITCH_MODE,
	MSG_RECORDER_START_STOP,
	MSG_GMA_RECORDER_START,
	MSG_ALARM_ENTRY_EXIT,

	MSG_APP_MESSAGE_MAX_INDEX, /*213*/
};

enum APP_UI_VIEW_ORDER {
	HIGHEST_ORDER,
	HIGH_ORDER,
	NORMAL_ORDER,
};

enum APP_UI_VIEW_ID {
	MAIN_VIEW = VIEW_ID_USER_OFFSET /* 1 */,
	BTMUSIC_VIEW,
	BTCALL_VIEW,
	TWS_VIEW,
	LCMUSIC_VIEW,
	LOOP_PLAYER_VIEW,
	LINEIN_VIEW,
	AUDIO_INPUT_VIEW,
	RECORDER_VIEW,
	USOUND_VIEW,
	CARD_READER_VIEW,
	CHARGER_VIEW,
	ALARM_VIEW,
	FM_VIEW,
	OTA_VIEW,
	CLOCK_VIEW,				// 16
	CLOCK_SELECTOR_VIEW,	// 17
	APPLIST_VIEW,			// 18
	SPORT_VIEW,				// 19
	HEART_VIEW,				// 20
	MSG_VIEW,				// 21
	COMPASS_VIEW,			// 22
	MUSIC_VIEW,				// 23
	HEALTH_BP_VIEW,			// 24
	HEALTH_SPO2_VIEW,		// 25
	POWER_VIEW,
	STOPWATCH_VIEW,
	ALARM_SET_VIEW,
	LOW_POWER_VIEW,

	AOD_CLOCK_VIEW,
	TEST_LONG_VIEW,

	CLOCK_SELECTOR_SUBVIEW_0,	// 32
	CLOCK_SELECTOR_SUBVIEW_1,
	CLOCK_SELECTOR_SUBVIEW_2,
	CLOCK_SELECTOR_SUBVIEW_3,
	CLOCK_SELECTOR_SUBVIEW_4,

	/* Test views to demo 'bar' shared with 3 views */
	TEST_TOP_VIEW1,
	TEST_TOP_VIEW2,
	TEST_TOP_VIEW3,
	TEST_BAR_VIEW,

	WELCOME_VIEW, // 41

	ALIPAY_MAIN_VIEW,		//42
	ALIPAY_BIND_VIEW, 		//43
	ALIPAY_PAY_VIEW, 		//44
	ALIPAY_UNBIND_VIEW, 	//45

	WXPAY_MAIN_VIEW,		//46
	WXPAY_BIND_VIEW, 		//47
	WXPAY_PAY_VIEW, 		//48
	WXPAY_UNBIND_VIEW, 		//49
};

enum APP_UI_MSGBOX_ID {
	/* must not less than MSGBOX_ID_USER_OFFSET */
	ALARM_MSGBOX_ID = 150,
	OTA_MSGBOX_ID   = 151,
	BTCALL_MSGBOX_ID = 152,
	LPOWER_MSGBOX_ID = 153,
};

enum APP_UI_EVENT_ID {
	UI_EVENT_NONE = 0,
	UI_EVENT_POWER_ON,
	UI_EVENT_POWER_OFF,
	UI_EVENT_STANDBY,
	UI_EVENT_WAKE_UP,

	UI_EVENT_LOW_POWER,
	UI_EVENT_NO_POWER,
	UI_EVENT_CHARGE,
	UI_EVENT_CHARGE_OUT,
	UI_EVENT_POWER_FULL,

	UI_EVENT_ENTER_PAIRING,
	UI_EVENT_CLEAR_PAIRED_LIST,
	UI_EVENT_WAIT_CONNECTION,
	UI_EVENT_CONNECT_SUCCESS,
	UI_EVENT_SECOND_DEVICE_CONNECT_SUCCESS,
	UI_EVENT_BT_DISCONNECT,
	UI_EVENT_TWS_START_TEAM,
	UI_EVENT_TWS_TEAM_SUCCESS,
	UI_EVENT_TWS_DISCONNECTED,
	UI_EVENT_TWS_PAIR_FAILED,

	UI_EVENT_VOLUME_CHANGED,
	UI_EVENT_MIN_VOLUME,
	UI_EVENT_MAX_VOLUME,

	UI_EVENT_PLAY_START,
	UI_EVENT_PLAY_PAUSE,
	UI_EVENT_PLAY_PREVIOUS,
	UI_EVENT_PLAY_NEXT,

	UI_EVENT_BT_INCOMING,
	UI_EVENT_BT_OUTGOING,
	UI_EVENT_BT_START_CALL,
	UI_EVENT_BT_ONGOING,
	UI_EVENT_BT_HANG_UP,
	UI_EVENT_START_SIRI,
	UI_EVENT_STOP_SIRI,
	UI_EVENT_BT_CALLRING,

	UI_EVENT_MIC_MUTE,
	UI_EVENT_MIC_MUTE_OFF,
	UI_EVENT_TAKE_PICTURES,
	UI_EVENT_FACTORY_DEFAULT,

	UI_EVENT_ENTER_BTMUSIC,
	UI_EVENT_ENTER_LINEIN,
	UI_EVENT_ENTER_USOUND,
	UI_EVENT_ENTER_SPDIF_IN,
	UI_EVENT_ENTER_I2SRX_IN,
	UI_EVENT_ENTER_SDMPLAYER,
	UI_EVENT_ENTER_UMPLAYER,
	UI_EVENT_ENTER_NORMPLAYER,
	UI_EVENT_ENTER_SDPLAYBACK,
	UI_EVENT_ENTER_UPLAYBACK,
	UI_EVENT_ENTER_RECORD,
	UI_EVENT_ENTER_MIC_IN,
	UI_EVENT_ENTER_FM,
};

struct event_strmap_s {
	int8_t event;
	const char *str;
};

struct event_ui_map {
	uint8_t  sys_event;
	uint8_t  ui_event;
};

#endif
