manifest:
  projects:
  - name: cmsis
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_HAL_CMSIS
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: thirdparty/hal/cmsis
  - name: fatfs
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_FS_FATFS
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: thirdparty/fs/fatfs
  - name: lvgl
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_LVGL
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: thirdparty/lib/gui/lvgl
  - name: alipay
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_ALIPAY
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: thirdparty/lib/alipay
  - name: alipay_wxpay
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_ALIPAY_WXPAY
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: thirdparty/lib/alipay_wxpay
  - name: mbedtls
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_CRYPTO_MBEDTLS
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: thirdparty/crypto/mbedtls
  - name: segger
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_DBG_SEGGER
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: thirdparty/debug/segger
  - name: tinycrypt
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_CRYPTO_TINYCRYPT
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: thirdparty/crypto/tinycrypt
  - name: littlefs
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_FS_LITTLEFS
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: thirdparty/fs/littlefs
  - name: bootloader
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_BOOT_LOADER
    revision: REL3__TAG_ZS308A_2700_220919_BF3
  - name: framework_base
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_FRAMEWORK_BASE
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: framework/base
  - name: framework_system
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_SYSTEM
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: framework/system
  - name: audio
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_AUDIO
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: framework/audio
  - name: media
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_MEDIA_BASE
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: framework/media
  - name: ota
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_OTA
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: framework/ota
  - name: bluetooth
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_BLUETOOTH
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: framework/bluetooth
  - name: display
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_DISPLAY
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: framework/display
  - name: usb
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_USB
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: framework/usb
  - name: sensor
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_LIB_SENSOR
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: framework/sensor
  - name: bt_watch
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_APPLICATION_BT_WATCH
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: application/bt_watch
  - name: bt_watch_call
    url: ssh://192.168.4.4:29418/ZH/actions/BT_WATCH_CALL
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: application/bt_watch_call
  - name: bt_watch_no_psram
    url: ssh://192.168.4.4:29418/ZH/actions/BT_WATCH_NO_PSRAM
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: application/bt_watch_no_psram
  - name: view_demo
    url: ssh://192.168.4.4:29418/ZH/actions/ZSDK_APPLICATION_VIEW_DEMO
    revision: REL3__TAG_ZS308A_2700_220919_BF3
    path: application/view_demo
  self:
    path: zephyr
    west-commands: scripts/west-commands.yml
