subdir-ccflags-y += -USYS_LOG_DOMAIN -DSYS_LOG_DOMAIN=\"system_app\"

obj-y += system_app_main.o system_app_shell.o 
obj-y += system_audio_policy.o system_app_launcher.o
obj-$(CONFIG_BT_CONTROLER_RF_FCC) += system_fcc_entry.o
