/* generated by UI-Editor, (c)2009 Actions Semiconductor */
#ifndef __LOGO_STY_H__
#define __LOGO_STY_H__

#define  SCENE_LOGO    0x3632cb4e
#define  PIC_LOGO    0xc6e13ee
#define  PIC_OTA    0x47fb3ecf

#endif /* #ifndef __LOGO_STY_H__ */
